### PR TITLE
Update continuous integration

### PR DESCRIPTION
**Pull request by sudomakeinstall**
This pull request removes the disabled continuous integration code (AppVeyor, CircleCI, Travis CI).  It then enables continuous integration through GitHub actions (in line with the ITKModuleTemplate repository).  Finally, it fixes compilation errors when building with python wrappers for scalar and RGB pixel types.  A fix was attempted for vector pixel types, but was not achieved due to errors indicating a missing comparison operator.  Wrapping for vector pixel types was therefore disabled.

### CODE REVIEW

**Comment by sudomakeinstall** [comment]
@dzenanz I don't think you can trigger github actions workflows via a fork--would it be possible for me to get permission to push branches directly to this repo?

**Comment by dzenanz** [comment]
I created a new team with maintainer access level and invited you to it @DVigneault. Tell me whether this is enough or not.

**Comment by sudomakeinstall** [comment]
@dzenanz Thanks so much!  Looks like that did the trick.

**Review by jhlegarreta — APPROVED** [review]
Nice Davis. Thanks for doing this.

**Review by thewtex — APPROVED** [review]

**Comment by sudomakeinstall** [comment]
Python wrapper tests now passing on all platforms!  Not sure what caused the mac and windows cxx tests to be cancelled, but looks like `build-test-cxx (ubuntu-18.04)` had passing tests, but then failed to submit to cdash.

**Pull request merged**
