### PR TITLE
Update itkv5rc2 comp

### PR DESCRIPTION
**Pull request by hjmjohnson**

### CODE REVIEW

**Comment by hjmjohnson** [comment]
@thewtex  Build errors with ANTs when building against this module.

**Comment by fbudin69500** [comment]
Looks reasonable but I need some time to look into the error on CI.

**Comment by hjmjohnson** [comment]
@fbudin69500 Can we merge before CI is fixed.  ANTs does not build without this change.

**Comment by fbudin69500** [comment]
Issue #10 opened to keep track of the problem.

**Pull request merged**
